apiVersion: v1
kind: Namespace
metadata:
  name: c2c-snap-aws-ns
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: c2c-snap-aws-config
  namespace: c2c-snap-aws-ns
data:
  SNAP_ENV: Dev

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c2c-snap-aws-deployment
  namespace: c2c-snap-aws-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 792373136340.dkr.ecr.us-east-2.amazonaws.com/cisco_pov:df81f4180a6e01e5811835acb0be708e7fa2ad45
          envFrom:
            - configMapRef:
                name: c2c-snap-aws-config

---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: c2c-snap-aws-label
  name: c2c-snap-aws-service
  namespace: c2c-snap-aws-ns
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer

---