apiVersion: v1
kind: Namespace
metadata:
  name: c2c-snap-aws-ns
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c2c-snap-aws-deployment
  namespace: c2c-snap-aws-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 792373136340.dkr.ecr.us-east-2.amazonaws.com/cisco_pov:53bd791370488bc597c1342a3664c090e97133a6

---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: c2c-snap-aws-label
  name: c2c-snap-aws-service
  namespace: c2c-snap-aws-ns
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer

---